# Just a comment.

ejikznayka.arithmetics:
  type: config_object
  label: 'Settings for mental arithmetics'
  mapping:
    digits:
      type: integer
      label: 'Digits'
    range:
      min:
        type: integer
        label: 'From'
      max:
        type: integer
        label: 'To'
    count:
      type: integer
      label: 'Number of numbers'
    interval:
      type: float
      label: 'Interval (seconds)'
    column:
      type: string
      label: 'Show numbers by one or in column?'
    font_size:
      type: integer
      label: 'Font size'
    random_location:
      type: boolean
      label: 'Random location'
    keep:
      type: boolean
      label: 'Keep or hide line or column after last number?'
    minus:
      type: boolean
      label: 'Subtraction allowed'
    mark:
      type: integer
      label: 'Mark for correct task'
    correct_emoticon:
      type: binary
      label: 'Smiley for correct answer'
    incorrect_emoticon:
      type: binary
      label: 'Smiley for incorrect answer'
    correct_audio:
      type: binary
      label: 'Audio for correct answer'
    incorrect_audio:
      type: binary
      label: 'Audio for incorrect answer'
